### ISSUE TITLE
Memberpress Test: Transactions are not getting expired. The user is able to select expiry date as less than the creation date.

### ISSUE THREAD

**Issue by Swetang11** [expresstechsoftware/connect-memberpress-discord-add-on#128]
Memberpress Test: Transactions are not getting expired. The user is able to select the expiry date as less than the creation date. 

The Expiry date should be less than the System date not less than the creation date.

![Transactions ‹ ExpressTech SoftWare — WordPress](https://user-images.githubusercontent.com/8683277/200921136-ff1c2384-0ac7-4da8-a1c5-4ba0d178160d.png)

**Comment by younes-dro** [comment]
The only reason for us to modify expiration dates lower than the creation date, to force a transaction to become "Expired" and this gives us a hand in testing the deletion of the discord role linked to this transaction.

other than that, it's up to the MemberPress team to decide if it can or it can't.
